#!/bin/bash
echo ""
clear
echo ""
echo -e ""
echo ""
echo ""
echo -e ""
echo -e " \e[91m[\e[92m*\e[91m]\e[1;93m Welcome to HACK-CAMERA Setup \e[0m"
echo ""
echo ""
echo ""

clear
echo ""
echo -e " \e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;32m Installing The HACK-CAMERA Tool Please Wait....  \e[0m"
echo -e ""
clear
echo ""
echo ""
echo -e "\e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;32m Installing The Hacking Camera Tool Please Wait....  \e[0m"
echo ""
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------  \e[1;91m\e[0m'
echo -e $'\e[1;96m\e[0m\e[1;77m\e[0m\e[1;96m\e[0m\e[1;91m  !!         DOWNLOAD REQUIREMENTS         !!\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------- \e[1;91m\e[0m'
echo ""
echo -e "\e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;32m \e[95m Muhammad Mehran \e[0m"
echo ""
sleep 2
echo -e "\e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;32m Cleaning old tunneler files... \e[0m"
rm -rf $HOME/.ngrokfolder $HOME/.cffolder
termux-setup-storage
apt-get update -y
apt-get upgrade -y
apt install php -y
apt install git -y
apt install wget -y
apt install curl -y
apt install openssh -y
apt install unzip -y
clear
echo '
      ---------------------------------   
    !!    Installation Successfull     !!  
      ---------------------------------   ' | lolcat
sleep 2
clear
echo
echo -e "\e[1m \e[36m[+] This is Last Step \e[m \e[21"
echo
echo
echo -e "\e[92m[+] Open New type this command:\e[93m bash hack_camera.sh \e[m "
echo
